---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Examine the Application"
      solveButton: false
    - name: module-02
      label: "Build the Image"
      solveButton: false
    - name: module-03
      label: "Test and Verify"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty

